RHELPLAN-68126 Collections - Nbde_server - fixing ansible-test errors (#31)
* RHELPLAN-68126 	Collections - Nbde_server - fixing ansible-test errors

- Removing obsolete tests/setup_module_utils.sh

* RHELPLAN-68126 - Collections - Nbde_server - fixing ansible-test errors

RHELPLAN-56179 - Add the __future__ boilerplate to all of the modules and module_utils code

ERROR: Found 1 future-import-boilerplate issue(s) which need to be resolved:
ERROR: plugins/modules/nbde_server_tang.py:0:0: missing: from __future__ import (absolute_import, division, print_function)
See documentation for help: https://docs.ansible.com/ansible/2.10/dev_guide/testing/sanity/future-import-boilerplate.html

* RHELPLAN-68126  Collections - Nbde_server - fixing ansible-test errors

Documentation parse error:
[ERROR]: unable to parse ansible_collections/fedora/linux_system_roles/plugins/modules/nbde_server_tang.py
ERROR! module fedora.linux_system_roles.nbde_server_tang missing documentation (or could not parse documentation):
mapping values are not allowed in this context

* RHELPLAN-68126 Collections - Nbde_server - fixing ansible-test errors

ERROR: Found 2 yamllint issue(s) which need to be resolved:
ERROR: plugins/modules/nbde_server_tang.py:93:24: error: EXAMPLES: syntax error: mapping values are not allowed here (syntax)
ERROR: plugins/modules/nbde_server_tang.py:93:24: unparsable-with-libyaml: None - mapping values are not allowed in this context
ERROR: plugins/modules/nbde_server_tang.py:104:10: error: EXAMPLES: syntax error: mapping values are not allowed here (syntax)
ERROR: plugins/modules/nbde_server_tang.py:104:10: unparsable-with-libyaml: None - mapping values are not allowed in this context

* RHELPLAN-68126 Collections - Nbde_server - fixing ansible-test errors

RHELPLAN-68789 - Collections - ignore file for each role

Adding .sanity-ansible-ignore-2.9.txt, which is compliant with the ignore file
handling implemented in "support for ansible-test #29".
https://github.com/linux-system-roles/tox-lsr/pull/29